# -*- coding: utf-8 -*-
"""ESTRUTURAS DE REPETIÇÃO.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/187UOBuLQkMtpzcySL3TagtG3DEpTg4Tf

Faça um programa que peça uma nota, entre zero e dez. Mostre uma mensagem caso o valor seja inválido e continue pedindo até que o usuário informe um valor válido.
"""

#while:
nota = float(input('digite a nota do aluno: '))
while nota<0 or nota>10:
  print('número inválido!')
  nota = float(input('digite a nota do aluno: '))

"""Faça um programa que imprima na tela apenas os números ímpares entre 1 e 50.

"""

#FOR
for i in range (1,10):
  print(i)

soma=0
for x in range (1,51):
  if x%2 > 0:
    soma +=x # soma=soma + x

print(soma)