# -*- coding: utf-8 -*-
"""função - 04/03

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hZxhHZOws13GBAwOFEVlainRjGRugr7K

1 - Faça um programa para imprimir:
1
 2 2
 3 3 3
.....
 n n n n n n ... n
"""

def imprimir_padrao(n):
    for i in range(1, n + 1):
        print((str(i) + ' ') * i)

# Teste
n = int(input("Digite o valor de n: "))
imprimir_padrao(n)

"""2 - Escreva uma função chamada fatorial que calcula o fatorial de um número inteiro fornecido como argumento."""

def fatorial(n):
    if n < 0:
        return None
    elif n == 0:
        return 1
    else:
        resultado = 1
        for i in range(1, n + 1):
            resultado *= i
        return resultado


print("Fatorial de 5:", fatorial(5))

"""3 - Escreva uma função chamada verifica_primo que verifica se um número é primo ou não e retorna True ou False."""

def verifica_primo(n):
    if n <= 1:
        return False
    for i in range(2, int(n**0.5) + 1):
        if n % i == 0:
            return False
    return True

print("Verifica se 7 é primo:", verifica_primo(7))

"""4 - Escreva uma função chamada inverte_string que aceita uma string como parâmetro e retorna a string invertida.

"""

def inverte_string(texto):
    invertido = ''
    for i in range(len(texto) - 1, -1, -1):
        invertido += texto[i]
    return invertido
print(inverte_string("oi professora, me passa de ano por dó, por favor."))

"""5 - Escreva uma função chamada maior_valor que aceita uma lista de números como parâmetro e retorna o maior valor na lista."""

def maior_valor(lista):
    if not lista:
        return None
    maior = lista[0]
    for x in lista:
        if x > maior:
            maior = x
    return maior
numeros = [10, 5, 8, 15, 3]
print("O maior valor na lista é:", maior_valor(numeros))

"""6 - Escreva uma função chamada conta_vogais que aceita uma string como parâmetro e retorna o número de vogais na string."""

def conta_vogais(texto):
    vogais = 'aeiou'
    contador = 0
    for letra in texto.lower():
        if letra in vogais:
            contador += 1
    return contador

