# -*- coding: utf-8 -*-
"""python - 07/03

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bUdnxcY6CCm_mk_9Mw1gAuSvjFrlzSds

1. Faça um programa que possua um Dicionário, adicione elementos ao dicionário e os mostre na tela.
"""

dicionario = {}
dicionario['nome'] = 'João'
dicionario['idade'] = 30
dicionario['cidade'] = 'São Paulo'
print("Dicionário:")
for chave, valor in dicionario.items():
    print(chave + ":", valor)

"""2. Faça um programa, utilizando Dicionários, que peça para o usuário inserir o nome de três produtos de mercado e seus respectivos preços e os mostre na tela."""

produtos = {}
for i in range(3):
    produto = input("Insira o nome do produto: ")
    preco = float(input("Insira o preço do produto em R$: "))
    produtos[produto] = preco
print("\nProdutos e Preços:")
for produto, preco in produtos.items():
    print(f"{produto}: R$ {preco:.2f}")

"""3. Faça um programa, utilizando Dicionários, que peça para o usuário inserir quatro notas e mostre na tela as notas e a média entre elas."""

notas = []
for i in range(4):
    nota = float(input(f"Insira a {i+1}ª nota: "))
    notas.append(nota)
media = sum(notas) / len(notas)
print("\nNotas inseridas:")
for i, nota in enumerate(notas):
    print(f"Nota {i+1}: {nota}")
print(f"Média: {media:.2f}")

"""4. Faça um programa, utilizando Dicionários, que:

1° Passo: Peça para o usuário inserir quatro coisas em uma “Caixa Misteriosa” .

2° Passo: Peça para o usuário inserir um número.

3° Passo: Mostre na tela o que foi inserido na posição do número inserido pelo usuário.
"""

caixamisteriosa = {}
print("Insira quatro coisas na Caixa Misteriosa:")
for i in range(4):
    coisa = input(f"Insira a {i+1}ª coisa: ")
    caixamisteriosa[i+1] = coisa
numero = int(input("\nInsira um número de 1 a 4 para revelar o que está na Caixa Misteriosa: "))
if numero < 1 or numero > 4:
    print("Número inválido! Por favor, insira um número de 1 a 4.")
else:
    coisanacaixa = caixamisteriosa[numero]
    print(f"Na posição {numero} da Caixa Misteriosa está: {coisanacaixa}")

"""5. Faça um programa, utilizando Dicionários, que:

1° Passo: Peça para o usuário inserir o nome de três funcionários e os mostre na tela.

2° Passo: Peça para o usuário demitir um funcionário e mostre na tela os funcionários restantes.
"""

funcionarios = {}
print("Passo 1: Inserir o nome de três funcionários")
for i in range(3):
    nome = input(f"Insira o nome do {i+1}º funcionário: ")
    funcionarios[i+1] = nome
print("\nFuncionários:")
for chave, valor in funcionarios.items():
    print(f"{chave}: {valor}")
numero_demissao = int(input("\nPasso 2: Demitir um funcionário. Insira o número do funcionário a ser demitido (1 a 3): "))
if numero_demissao < 1 or numero_demissao > 3:
    print("Número inválido! Por favor, insira um número de 1 a 3.")
else:
    funcionarios.pop(numero_demissao)
    print("\nFuncionários restantes após a demissão:")
    for chave, valor in funcionarios.items():
        print(f"{chave}: {valor}")