# -*- coding: utf-8 -*-
"""Python - 3* (29/02)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Qog5-6A0Oyd_ZxbkGWAd3fZhc1Ov-VRA

1 - Faça um programa que peça uma nota, entre zero e dez. Mostre uma mensagem caso o valor seja inválido e continue pedindo até que o usuário informe um valor válido.
"""

#while:
nota = float(input('digite a nota:'))
while nota<0 or nota>10:
    print('nota invalida!')
    nota = float(input('digite a nota:'))

"""2 - Faça um programa que leia um nome de usuário e a sua senha e não aceite a senha igual ao nome do usuário, mostrando uma mensagem de erro e voltando a pedir as informações."""

#while:
nome = float(input('digite seu nome: '))
senha = float(input('digite a senha: '))
while senha == nome:
    print('senha invalida!')
    senha = float(input('digite novamente a senha: '))