# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jV5Q6xLIZCwdgPvZIxa9WH7zXXi2HK8y

1 - Faça um Programa que peça um valor e mostre na tela se o valor é positivo ou negativo.
"""

n1 = float(input("digite um número, por gentileza:"))
if n1<0:
    print("seu número é negativo!")
else:
    print("seu número é positivo!")

"""2 - Faça um Programa que verifique se uma letra digitada é "F" ou "M". Conforme a letra escrever: F - Feminino, M - Masculino, Sexo Inválido.

"""

n1 = input("informe seu genêro, correspondente a F ou M: ")
if  n1 == 'F':
    print("seu genêro é Feminino!")
elif n1 == 'M':
    print ("seu genênero é Masculino!")
else:
    print("genêro inavalido!")

"""3 - Faça um Programa que verifique se uma letra digitada é vogal ou consoante."""

n1 = input("informe uma letra:")
n1 = n1.lower()
if n1 in ('a','e','i','o','u'):
    print('sua letra é uma vogal')
else :
    print('sua letra é uma consoante')



"""5 - Faça um Programa que leia três números e mostre o maior deles.

"""

n1 = float(input("digite um número, por gentileza:"))
n2 = float(input("digite outro número, por gentileza:"))
n3 = float(input("digite o ultimo número, por gentileza:"))
if n1>n2 and n1>n3:
    print("o maior número é:", n1)

elif n2>n3 and n2>n1:
    print("o maior número é:", n2)

else n3>n1:
    print("o maior número é:",n3)

